feat: submitProposal() & addEvidence() functions fixed
zenbitETH/zengo pull request #78
Opened 2023-09-21 22:48 UTC by Markkos89

submitProposal() & addEvidence() functions fixed

2023-09-22 14:40 UTC, HabacucMX reviewed
![Screenshot 2023-09-22 at 8 33 24](https://github.com/zenbitETH/zengo/assets/57845110/7e5945f3-5f15-4ef4-a02b-a6c1ab80201a)

There seems to be a conflict in the update from `ipfsURL` to `ipfsURI` in lines `111` and `158`,  from **apps/application/contexts/ProposalsContext.tsx**. also in line `4` from: **apps/application/interfaces/index.ts**

2023-09-24 15:49 UTC, HabacucMX approved these changes
The eslint is messing up the comparison between versions, but this could work to comment on the contract changes. The left/red is the #78 code, while the code on dev is right/green:

![Screenshot 2023-09-24 at 9 29 13](https://github.com/zenbitETH/zengo/assets/57845110/469d3284-ac87-4fea-af8d-a302fa0a99df) 
![Screenshot 2023-09-24 at 9 33 17](https://github.com/zenbitETH/zengo/assets/57845110/929403f7-1d82-4fc4-a5bc-2e6fa015a3ff) 1. The `streetAddress`, `_latitude` and `_longitude` were added to the `SubmitProposal` function in the `zengo.sol` contract.


![Screenshot 2023-09-24 at 9 38 20](https://github.com/zenbitETH/zengo/assets/57845110/bceb7886-c55f-4e9c-8a14-84dbaf69b2b0) 2. those were also added to the `ZengoStorage.sol` contract...

![Screenshot 2023-09-24 at 9 42 03](https://github.com/zenbitETH/zengo/assets/57845110/8ac8f59d-c4e5-41f3-9bad-c603abea7088) 3. and also in the `structs.sol` from the `libs` folder


Those were the changes I have identified in the contracts. There are minor issues with the styles that can be corrected in a future PR
1. Icons are overlapping with the logo in the mobile header
2. The header has a fixed color in some screens, it should be transparent with a backdrop blur

2023-09-24 22:24 UTC, Markkos89 commented
> The eslint is messing up the comparison between versions, but this could work to comment on the contract changes. The left/red is the #78 code, while the code on dev is right/green:
> 
> ![Screenshot 2023-09-24 at 9 29 13](https://user-images.githubusercontent.com/57845110/270174682-469d3284-ac87-4fea-af8d-a302fa0a99df.png) ![Screenshot 2023-09-24 at 9 33 17](https://user-images.githubusercontent.com/57845110/270174948-929403f7-1d82-4fc4-a5bc-2e6fa015a3ff.png) 1. The `streetAddress`, `_latitude` and `_longitude` were added to the `SubmitProposal` function in the `zengo.sol` contract.
> 
> ![Screenshot 2023-09-24 at 9 38 20](https://user-images.githubusercontent.com/57845110/270175181-bceb7886-c55f-4e9c-8a14-84dbaf69b2b0.png) 2. those were also added to the `ZengoStorage.sol` contract...
> 
> ![Screenshot 2023-09-24 at 9 42 03](https://user-images.githubusercontent.com/57845110/270175390-8ac8f59d-c4e5-41f3-9bad-c603abea7088.png) 3. and also in the `structs.sol` from the `libs` folder
> 
> Those were the changes I have identified in the contracts. There are minor issues with the styles that can be corrected in a future PR
> 
> 1. Icons are overlapping with the logo in the mobile header
> 2. The header has a fixed color in some screens, it should be transparent with a backdrop blur

@HabacucMX 

Those changes are on #78's branch and this code is a checkout from `dev`, to `dev` 
#78 isn't merged yet, so `dev` doesn't have it.

I'm a little bit confused, should I merge? or include the #78 code here too? :confused:

2023-09-28 23:57 UTC, shyam-patel-kira requested changes

2023-09-28 23:57 UTC, shyam-patel-kira commented on apps/contracts/contracts/Zengo.sol
> +        string memory _streetAddress,
@Markkos89 Can you group all the dataType declaration? It will use less gas and is a standard practice

2023-09-28 23:57 UTC, shyam-patel-kira commented on apps/contracts/contracts/lib/Structs.sol
> +        string streetAddress;
same for the struct as well

2023-09-30 01:08 UTC, Markkos89 commented on apps/contracts/contracts/lib/Structs.sol
> +        string streetAddress;
updated!

2023-09-30 01:29 UTC, merged